name: inforcom
description: "Inforcom Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Подключаемые пакеты:
  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar_v2: ^6.1.0
  flutter_svg: ^2.2.0
  mask_text_input_formatter: ^2.9.0
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.1.1
  go_router: ^15.1.3
  url_launcher: 
  yandex_maps_mapkit:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/map_icons/
    - assets/bottom_icons/
    - assets/icons/
    - assets/images/
    - assets/images/logos/


  # Подключаемые шрифты:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont.ttf
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/RobotoFlex-VariableFont.ttf
  
